a = int(input("enter a number:"))
b = int(input("enter a number:"))
sum = float(a+b)
sub = float(a-b)
mul = a*b
div = float(a/b)
print("sum of a and b:",sum)
print("sub of a and b:",sub)
print("mul of a and b:",mul)
print("div of a and b:",div)
